agent {
    data_dir          = "/opt/spire/data/agent"
    log_level         = "INFO"
    server_address    = "spire-server"
    server_port       = "8081"
    socket_path       = "/run/spire/sockets/agent.sock"
    trust_bundle_path = "/opt/spire/conf/agent/bootstrap.crt"
    trust_domain      = "zt.local"

    # Insecure bootstrap — acceptable for E2E testing only
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
