agent {
    data_dir          = "/tmp/spire-agent/data"
    log_level         = "DEBUG"
    server_address    = "$SPIRE_SERVER_ADDRESS"
    server_port       = "$SPIRE_SERVER_PORT"
    socket_path       = "/run/spire/sockets/agent.sock"
    trust_domain      = "zt.local"

    insecure_bootstrap = true
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path  = "/opt/spire/conf/agent/agent.key.pem"
            certificate_path  = "/opt/spire/conf/agent/agent.crt.pem"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
