<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace GPBMetadata;

class Workloadapi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
œ
workloadapi.protospiffe.workload"
X509SVIDRequest"Ö
X509SVIDResponse(
svids (2.spiffe.workload.X509SVID
crl (R
federated_bundles (27.spiffe.workload.X509SVIDResponse.FederatedBundlesEntry7
FederatedBundlesEntry
key (	
value (:8"e
X509SVID
	spiffe_id (	
	x509_svid (
x509_svid_key (
bundle (
hint (	"
X509BundlesRequest"‰
X509BundlesResponseB
bundles (21.spiffe.workload.X509BundlesResponse.BundlesEntry.
BundlesEntry
key (	
value (:8"5
JWTSVIDRequest
audience (	
	spiffe_id (	":
JWTSVIDResponse\'
svids (2.spiffe.workload.JWTSVID"8
JWTSVID
	spiffe_id (	
svid (	
hint (	"
JWTBundlesRequest"‡
JWTBundlesResponseA
bundles (20.spiffe.workload.JWTBundlesResponse.BundlesEntry.
BundlesEntry
key (	
value (:8"8
ValidateJWTSVIDRequest
svid (	
audience (	"U
ValidateJWTSVIDResponse
	spiffe_id (	\'
claims (2.google.protobuf.Struct2ã
SpiffeWorkloadAPIV
FetchX509SVID .spiffe.workload.X509SVIDRequest!.spiffe.workload.X509SVIDResponse0_
FetchX509Bundles#.spiffe.workload.X509BundlesRequest$.spiffe.workload.X509BundlesResponse0Q
FetchJWTSVID.spiffe.workload.JWTSVIDRequest .spiffe.workload.JWTSVIDResponse\\
FetchJWTBundles".spiffe.workload.JWTBundlesRequest#.spiffe.workload.JWTBundlesResponse0d
ValidateJWTSVID\'.spiffe.workload.ValidateJWTSVIDRequest(.spiffe.workload.ValidateJWTSVIDResponseB6Z4github.com/spiffe/go-spiffe/v2/proto/spiffe/workloadbproto3'
        , true);

        static::$is_initialized = true;
    }
}

