<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The JWTSVIDResponse message conveys JWT-SVIDs.
 *
 * Generated from protobuf message <code>spiffe.workload.JWTSVIDResponse</code>
 */
class JWTSVIDResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The list of returned JWT-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.JWTSVID svids = 1;</code>
     */
    private $svids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spiffe\Workload\JWTSVID[]|\Google\Protobuf\Internal\RepeatedField $svids
     *           Required. The list of returned JWT-SVIDs.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The list of returned JWT-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.JWTSVID svids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSvids()
    {
        return $this->svids;
    }

    /**
     * Required. The list of returned JWT-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.JWTSVID svids = 1;</code>
     * @param \Spiffe\Workload\JWTSVID[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSvids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spiffe\Workload\JWTSVID::class);
        $this->svids = $arr;

        return $this;
    }

}

