<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The X509SVIDResponse message conveys X.509-SVIDs.
 *
 * Generated from protobuf message <code>spiffe.workload.X509SVIDResponse</code>
 */
class X509SVIDResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The list of returned X.509-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.X509SVID svids = 1;</code>
     */
    private $svids;
    /**
     * Optional. ASN.1 DER encoded certificate revocation lists.
     *
     * Generated from protobuf field <code>repeated bytes crl = 2;</code>
     */
    private $crl;
    /**
     * Optional. CA certificate bundles for federating with foreign trust domains.
     * Bundles are ASN.1 DER encoded.
     *
     * Generated from protobuf field <code>map<string, bytes> federated_bundles = 3;</code>
     */
    private $federated_bundles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spiffe\Workload\X509SVID[]|\Google\Protobuf\Internal\RepeatedField $svids
     *           Required. The list of returned X.509-SVIDs.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $crl
     *           Optional. ASN.1 DER encoded certificate revocation lists.
     *     @type array|\Google\Protobuf\Internal\MapField $federated_bundles
     *           Optional. CA certificate bundles for federating with foreign trust domains.
     *           Bundles are ASN.1 DER encoded.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The list of returned X.509-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.X509SVID svids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSvids()
    {
        return $this->svids;
    }

    /**
     * Required. The list of returned X.509-SVIDs.
     *
     * Generated from protobuf field <code>repeated .spiffe.workload.X509SVID svids = 1;</code>
     * @param \Spiffe\Workload\X509SVID[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSvids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spiffe\Workload\X509SVID::class);
        $this->svids = $arr;

        return $this;
    }

    /**
     * Optional. ASN.1 DER encoded certificate revocation lists.
     *
     * Generated from protobuf field <code>repeated bytes crl = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCrl()
    {
        return $this->crl;
    }

    /**
     * Optional. ASN.1 DER encoded certificate revocation lists.
     *
     * Generated from protobuf field <code>repeated bytes crl = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->crl = $arr;

        return $this;
    }

    /**
     * Optional. CA certificate bundles for federating with foreign trust domains.
     * Bundles are ASN.1 DER encoded.
     *
     * Generated from protobuf field <code>map<string, bytes> federated_bundles = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFederatedBundles()
    {
        return $this->federated_bundles;
    }

    /**
     * Optional. CA certificate bundles for federating with foreign trust domains.
     * Bundles are ASN.1 DER encoded.
     *
     * Generated from protobuf field <code>map<string, bytes> federated_bundles = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFederatedBundles($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->federated_bundles = $arr;

        return $this;
    }

}

