<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The X509BundlesRequest message conveys parameters for requesting X.509
 * bundles. There are currently no request parameters.
 *
 * Generated from protobuf message <code>spiffe.workload.X509BundlesRequest</code>
 */
class X509BundlesRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

}

