<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The X509SVID message carries a single SVID and all associated information,
 * including the private key and bundle.
 *
 * Generated from protobuf message <code>spiffe.workload.X509SVID</code>
 */
class X509SVID extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The SPIFFE ID of the X.509-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     */
    protected $spiffe_id = '';
    /**
     * Required. ASN.1 DER encoded X.509 certificate chain. The leaf certificate
     * (or SVID itself) MUST come first, followed by any intermediates.
     *
     * Generated from protobuf field <code>bytes x509_svid = 2;</code>
     */
    protected $x509_svid = '';
    /**
     * Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted.
     *
     * Generated from protobuf field <code>bytes x509_svid_key = 3;</code>
     */
    protected $x509_svid_key = '';
    /**
     * Required. ASN.1 DER encoded X.509 bundle for the trust domain.
     *
     * Generated from protobuf field <code>bytes bundle = 4;</code>
     */
    protected $bundle = '';
    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 5;</code>
     */
    protected $hint = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spiffe_id
     *           Required. The SPIFFE ID of the X.509-SVID.
     *     @type string $x509_svid
     *           Required. ASN.1 DER encoded X.509 certificate chain. The leaf certificate
     *           (or SVID itself) MUST come first, followed by any intermediates.
     *     @type string $x509_svid_key
     *           Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted.
     *     @type string $bundle
     *           Required. ASN.1 DER encoded X.509 bundle for the trust domain.
     *     @type string $hint
     *           Optional. A hint that can be used by a workload when more than one SVID is
     *           returned. For example, "internal" or "external" to denote an SVID for
     *           internal or external use, respectively.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The SPIFFE ID of the X.509-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @return string
     */
    public function getSpiffeId()
    {
        return $this->spiffe_id;
    }

    /**
     * Required. The SPIFFE ID of the X.509-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpiffeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spiffe_id = $var;

        return $this;
    }

    /**
     * Required. ASN.1 DER encoded X.509 certificate chain. The leaf certificate
     * (or SVID itself) MUST come first, followed by any intermediates.
     *
     * Generated from protobuf field <code>bytes x509_svid = 2;</code>
     * @return string
     */
    public function getX509Svid()
    {
        return $this->x509_svid;
    }

    /**
     * Required. ASN.1 DER encoded X.509 certificate chain. The leaf certificate
     * (or SVID itself) MUST come first, followed by any intermediates.
     *
     * Generated from protobuf field <code>bytes x509_svid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setX509Svid($var)
    {
        GPBUtil::checkString($var, False);
        $this->x509_svid = $var;

        return $this;
    }

    /**
     * Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted.
     *
     * Generated from protobuf field <code>bytes x509_svid_key = 3;</code>
     * @return string
     */
    public function getX509SvidKey()
    {
        return $this->x509_svid_key;
    }

    /**
     * Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted.
     *
     * Generated from protobuf field <code>bytes x509_svid_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setX509SvidKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->x509_svid_key = $var;

        return $this;
    }

    /**
     * Required. ASN.1 DER encoded X.509 bundle for the trust domain.
     *
     * Generated from protobuf field <code>bytes bundle = 4;</code>
     * @return string
     */
    public function getBundle()
    {
        return $this->bundle;
    }

    /**
     * Required. ASN.1 DER encoded X.509 bundle for the trust domain.
     *
     * Generated from protobuf field <code>bytes bundle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBundle($var)
    {
        GPBUtil::checkString($var, False);
        $this->bundle = $var;

        return $this;
    }

    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 5;</code>
     * @return string
     */
    public function getHint()
    {
        return $this->hint;
    }

    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHint($var)
    {
        GPBUtil::checkString($var, True);
        $this->hint = $var;

        return $this;
    }

}

