<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The JWTBundlesRequest message conveys parameters for requesting JWT bundles.
 * There are currently no such parameters.
 *
 * Generated from protobuf message <code>spiffe.workload.JWTBundlesRequest</code>
 */
class JWTBundlesRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

}

