<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The JWTBundlesResponse conveys JWT bundles.
 *
 * Generated from protobuf message <code>spiffe.workload.JWTBundlesResponse</code>
 */
class JWTBundlesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
     * domain.
     *
     * Generated from protobuf field <code>map<string, bytes> bundles = 1;</code>
     */
    private $bundles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $bundles
     *           Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
     *           domain.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
     * domain.
     *
     * Generated from protobuf field <code>map<string, bytes> bundles = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getBundles()
    {
        return $this->bundles;
    }

    /**
     * Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
     * domain.
     *
     * Generated from protobuf field <code>map<string, bytes> bundles = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setBundles($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->bundles = $arr;

        return $this;
    }

}

