<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The JWTSVIDRequest message conveys parameters for requesting JWT-SVIDs.
 *
 * Generated from protobuf message <code>spiffe.workload.JWTSVIDRequest</code>
 */
class JWTSVIDRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The audience(s) the workload intends to authenticate against.
     *
     * Generated from protobuf field <code>repeated string audience = 1;</code>
     */
    private $audience;
    /**
     * Optional. If a SPIFFE ID is provided, only the JWT-SVID for that SPIFFE
     * ID is returned.
     *
     * Generated from protobuf field <code>string spiffe_id = 2;</code>
     */
    protected $spiffe_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $audience
     *           Required. The audience(s) the workload intends to authenticate against.
     *     @type string $spiffe_id
     *           Optional. If a SPIFFE ID is provided, only the JWT-SVID for that SPIFFE
     *           ID is returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The audience(s) the workload intends to authenticate against.
     *
     * Generated from protobuf field <code>repeated string audience = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudience()
    {
        return $this->audience;
    }

    /**
     * Required. The audience(s) the workload intends to authenticate against.
     *
     * Generated from protobuf field <code>repeated string audience = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudience($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->audience = $arr;

        return $this;
    }

    /**
     * Optional. If a SPIFFE ID is provided, only the JWT-SVID for that SPIFFE
     * ID is returned.
     *
     * Generated from protobuf field <code>string spiffe_id = 2;</code>
     * @return string
     */
    public function getSpiffeId()
    {
        return $this->spiffe_id;
    }

    /**
     * Optional. If a SPIFFE ID is provided, only the JWT-SVID for that SPIFFE
     * ID is returned.
     *
     * Generated from protobuf field <code>string spiffe_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpiffeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spiffe_id = $var;

        return $this;
    }

}

