<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The JWTSVID message carries the JWT-SVID token and associated metadata.
 *
 * Generated from protobuf message <code>spiffe.workload.JWTSVID</code>
 */
class JWTSVID extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The SPIFFE ID of the JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     */
    protected $spiffe_id = '';
    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 2;</code>
     */
    protected $svid = '';
    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 3;</code>
     */
    protected $hint = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spiffe_id
     *           Required. The SPIFFE ID of the JWT-SVID.
     *     @type string $svid
     *           Required. Encoded JWT using JWS Compact Serialization.
     *     @type string $hint
     *           Optional. A hint that can be used by a workload when more than one SVID is
     *           returned. For example, "internal" or "external" to denote an SVID for
     *           internal or external use, respectively.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The SPIFFE ID of the JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @return string
     */
    public function getSpiffeId()
    {
        return $this->spiffe_id;
    }

    /**
     * Required. The SPIFFE ID of the JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpiffeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spiffe_id = $var;

        return $this;
    }

    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 2;</code>
     * @return string
     */
    public function getSvid()
    {
        return $this->svid;
    }

    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSvid($var)
    {
        GPBUtil::checkString($var, True);
        $this->svid = $var;

        return $this;
    }

    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 3;</code>
     * @return string
     */
    public function getHint()
    {
        return $this->hint;
    }

    /**
     * Optional. A hint that can be used by a workload when more than one SVID is
     * returned. For example, "internal" or "external" to denote an SVID for
     * internal or external use, respectively.
     *
     * Generated from protobuf field <code>string hint = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHint($var)
    {
        GPBUtil::checkString($var, True);
        $this->hint = $var;

        return $this;
    }

}

