<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The ValidateJWTSVIDRequest message conveys parameters for validating a
 * JWT-SVID.
 *
 * Generated from protobuf message <code>spiffe.workload.ValidateJWTSVIDRequest</code>
 */
class ValidateJWTSVIDRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 1;</code>
     */
    protected $svid = '';
    /**
     * Required. The audience the workload expects to authenticate against.
     *
     * Generated from protobuf field <code>string audience = 2;</code>
     */
    protected $audience = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $svid
     *           Required. Encoded JWT using JWS Compact Serialization.
     *     @type string $audience
     *           Required. The audience the workload expects to authenticate against.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 1;</code>
     * @return string
     */
    public function getSvid()
    {
        return $this->svid;
    }

    /**
     * Required. Encoded JWT using JWS Compact Serialization.
     *
     * Generated from protobuf field <code>string svid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSvid($var)
    {
        GPBUtil::checkString($var, True);
        $this->svid = $var;

        return $this;
    }

    /**
     * Required. The audience the workload expects to authenticate against.
     *
     * Generated from protobuf field <code>string audience = 2;</code>
     * @return string
     */
    public function getAudience()
    {
        return $this->audience;
    }

    /**
     * Required. The audience the workload expects to authenticate against.
     *
     * Generated from protobuf field <code>string audience = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAudience($var)
    {
        GPBUtil::checkString($var, True);
        $this->audience = $var;

        return $this;
    }

}

