<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadapi.proto

namespace Spiffe\Workload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The ValidateJWTSVIDResponse message conveys the JWT-SVID validation results.
 *
 * Generated from protobuf message <code>spiffe.workload.ValidateJWTSVIDResponse</code>
 */
class ValidateJWTSVIDResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The SPIFFE ID of the validated JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     */
    protected $spiffe_id = '';
    /**
     * Required. Claims contained within the payload of the validated JWT-SVID.
     * This includes both SPIFFE-required and non-required claims.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct claims = 2;</code>
     */
    protected $claims = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spiffe_id
     *           Required. The SPIFFE ID of the validated JWT-SVID.
     *     @type \Google\Protobuf\Struct $claims
     *           Required. Claims contained within the payload of the validated JWT-SVID.
     *           This includes both SPIFFE-required and non-required claims.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workloadapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The SPIFFE ID of the validated JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @return string
     */
    public function getSpiffeId()
    {
        return $this->spiffe_id;
    }

    /**
     * Required. The SPIFFE ID of the validated JWT-SVID.
     *
     * Generated from protobuf field <code>string spiffe_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpiffeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spiffe_id = $var;

        return $this;
    }

    /**
     * Required. Claims contained within the payload of the validated JWT-SVID.
     * This includes both SPIFFE-required and non-required claims.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct claims = 2;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getClaims()
    {
        return $this->claims;
    }

    public function hasClaims()
    {
        return isset($this->claims);
    }

    public function clearClaims()
    {
        unset($this->claims);
    }

    /**
     * Required. Claims contained within the payload of the validated JWT-SVID.
     * This includes both SPIFFE-required and non-required claims.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct claims = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setClaims($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->claims = $var;

        return $this;
    }

}

