agent {
  data_dir = "/opt/spire/data/agent"
  log_level = "DEBUG"
  server_address = "10.1.1.209"
  server_port = "8081"
  socket_path = "/run/spire/sockets/agent.sock"
  insecure_bootstrap = true
  trust_domain = "zt.local"
}

plugins {
  NodeAttestor "x509pop" {
    plugin_data {
      private_key_path = "/opt/spire/conf/agent/agent.key.pem"
      certificate_path = "/opt/spire/conf/agent/agent.crt.pem"
    }
  }

  KeyManager "disk" {
    plugin_data {
      directory = "/opt/spire/data/agent"
    }
  }

  WorkloadAttestor "unix" {
    plugin_data {
    }
  }
}
